import * as fs from "fs"

import * as cn from "./resume_cn.json"
import * as en from "./resume_en.json"

const dicEnUS = {
    basics:{
        basics:"basics",
        name:"name",
        birthPlace:"birth place",
        label:"label",
        phone:"phone",
        summary:"summary",
        url:"url",
    },
    education:{
        education:"education",
        institution:"institution",
        startDate:"start date",
        endDate:"end date",
        area:"area",
        studyType:"study type",
    },
    skills:{
        skills:"skills",
        name:"name",
        proficiency:"proficiency",
        keywords:"keywords",
    },
    work:{
        startDate:"start date",
        endDate:"end date",
        work:"work",
        name:"name",
        position:"position",
    },
    languages:{
        languages:"languages",
        language:"language",
        level:"level",
    },
    projects:{
        projects:"projects",
        name:"name",
        type:"type",
        entity:"entity",
        highlights:"highlights",
        keywords:"keywords",
        description:"description",
        roles:"roles",
    }
}

const dicZhCmnHans: typeof dicEnUS = {
    basics:{
        basics:"基本情况",
        name:"姓名",
        birthPlace:"出生地",
        label:"职位",
        phone:"电话",
        summary:"概述",
        url:"个人主页",
    },
    education:{
        education:"教育情况",
        institution:"教育机构",
        startDate:"开始日期",
        endDate:"结束日期",
        area:"专业",
        studyType:"类型",
    },
    skills:{
        skills:"职业技能",
        name:"技能",
        proficiency:"熟练度",
        keywords:"关键词",
    },
    work:{
        startDate:"开始日期",
        endDate:"结束日期",
        work:"工作经历",
        name:"企业名称",
        position:"职位",
    },
    languages:{
        languages:"语言",
        language:"语言",
        level:"水平",
    },
    projects:{
        projects:"项目经验",
        name:"名称",
        type:"类型",
        entity:"企业名称",
        highlights:"重点",
        keywords:"关键词",
        description:"描述",
        roles:"我的角色",
    }
}

const i18n:{[k:string]:typeof dicEnUS} = {
    'zh-cmn-Hans':dicZhCmnHans,
    'en-US':dicEnUS
}

const fields = (data:any,dic:any,columns:number)=>{
    return `<div style="display:flex; flex-wrap:wrap; ">
        ${
            Object.keys(data).filter(k=>k in dic).map(k=>{
                return `<div style="flex: 1 1 ${100/columns}%; display: flex;">
                    <span style="flex: 0 0 200px; ">${dic[k]}:</span>
                    <span style="flex: 0 0 calc(100% - 200px); ">${data[k]}</span>
                </div>`
            }).join("")
        }
    </div>`
}

const template  = (lang:string,data:typeof cn)=>{
    const dic = i18n[lang]
    return `<html>
        <head lang="${lang}">
            <title>${data.basics.name} | ${data.basics.label}</title>
            <style>
                body{
                    margin: 0;
                }
                section{
                    position: relative;
                    padding: 0px 8px;
                    max-width: 800px;
                    margin-left: auto;
                    margin-right:auto;
                }
                h1{
                    text-align: left;
                    padding-left: 20px;
                    border-bottom: 2px solid #000;
                }
                @media print {
                    section {page-break-inside: avoid;}
                }
            </style>
        </head>
        <body>
            ${
                Object.keys(data).filter(k=>k in dic).map(k=>{
                    return `
                    <section>
                        <h1>${dic[k][k]}</h1>
                        <div>
                            ${
                                data[k] instanceof Array ? data[k].map(x=>{
                                    return `<div style="margin-bottom: 16px;">${fields(x,dic[k],1)}</div>`
                                }).join("") : fields(data[k],dic[k],1)
                            }
                        </div>
                    </section>`
                }).join("")
            }
            <footer style="opacity: 0.05">
                generated by <a href="https://github.com/buhichan/json-resume-generator">json-resume-generator</a>
            </footer>   
        </body>
    </html>`;
}

const dic = {
    'zh-cmn-Hans':cn,
    'en-US':en
}

Object.keys(dic).forEach((x)=>{
    const rendered = template(x,dic[x])
    fs.writeFileSync('./output/'+x+".html",rendered)
})
       
