"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs = require("fs");
var cn = require("./resume_cn.json");
var en = require("./resume_en.json");
var dicEnUS = {
    basics: {
        basics: "basics",
        name: "name",
        birthPlace: "birth place",
        label: "label",
        phone: "phone",
        email: "email",
        summary: "summary",
        url: "url",
    },
    education: {
        education: "education",
        institution: "institution",
        startDate: "start date",
        endDate: "end date",
        area: "area",
        studyType: "study type",
    },
    skills: {
        skills: "skills",
        name: "name",
        proficiency: "proficiency",
        keywords: "keywords",
    },
    work: {
        startDate: "start date",
        endDate: "end date",
        work: "work",
        name: "name",
        position: "position",
    },
    languages: {
        languages: "languages",
        language: "language",
        level: "level",
    },
    projects: {
        projects: "projects",
        name: "name",
        type: "type",
        entity: "entity",
        highlights: "highlights",
        keywords: "keywords",
        description: "description",
        roles: "roles",
    }
};
var dicZhCmnHans = {
    basics: {
        basics: "基本情况",
        name: "姓名",
        birthPlace: "出生地",
        label: "职位",
        phone: "电话",
        email: "邮箱",
        summary: "概述",
        url: "个人主页",
    },
    education: {
        education: "教育情况",
        institution: "教育机构",
        startDate: "开始日期",
        endDate: "结束日期",
        area: "专业",
        studyType: "类型",
    },
    skills: {
        skills: "职业技能",
        name: "技能",
        proficiency: "熟练度",
        keywords: "关键词",
    },
    work: {
        startDate: "开始日期",
        endDate: "结束日期",
        work: "工作经历",
        name: "企业名称",
        position: "职位",
    },
    languages: {
        languages: "语言",
        language: "语言",
        level: "水平",
    },
    projects: {
        projects: "项目经验",
        name: "名称",
        type: "类型",
        entity: "企业名称",
        highlights: "重点",
        keywords: "关键词",
        description: "描述",
        roles: "我的角色",
    }
};
var i18n = {
    'zh-cmn-Hans': dicZhCmnHans,
    'en-US': dicEnUS
};
var fields = function (data, dic, columns) {
    return "<div style=\"display:flex; flex-wrap:wrap; \">\n        " + Object.keys(data).filter(function (k) { return k in dic; }).map(function (k) {
        return "<div style=\"flex: 1 1 " + 100 / columns + "%; display: flex;\">\n                    <span style=\"flex: 0 0 200px; \">" + dic[k] + ":</span>\n                    <span style=\"flex: 0 0 calc(100% - 200px); \">" + data[k] + "</span>\n                </div>";
    }).join("") + "\n    </div>";
};
var template = function (lang, data) {
    var dic = i18n[lang];
    return "<html>\n        <head lang=\"" + lang + "\">\n            <title>" + data.basics.name + " | " + data.basics.label + "</title>\n            <style>\n                body{\n                    margin: 0;\n                }\n                section{\n                    position: relative;\n                    padding: 0px 8px;\n                    max-width: 800px;\n                    margin-left: auto;\n                    margin-right:auto;\n                }\n                h1{\n                    text-align: left;\n                    padding-left: 20px;\n                    border-bottom: 2px solid #000;\n                }\n                @media print {\n                    section {page-break-inside: avoid;}\n                }\n            </style>\n        </head>\n        <body>\n            " + Object.keys(data).filter(function (k) { return k in dic; }).map(function (k) {
        return "\n                    <section>\n                        <h1>" + dic[k][k] + "</h1>\n                        <div>\n                            " + (data[k] instanceof Array ? data[k].map(function (x) {
            return "<div style=\"margin-bottom: 16px;\">" + fields(x, dic[k], 1) + "</div>";
        }).join("") : fields(data[k], dic[k], 1)) + "\n                        </div>\n                    </section>";
    }).join("") + "\n            <footer style=\"opacity: 0.05\">\n                generated by <a href=\"https://github.com/buhichan/json-resume-generator\">json-resume-generator</a>\n            </footer>   \n        </body>\n    </html>";
};
var dic = {
    'zh-cmn-Hans': cn,
    'en-US': en
};
Object.keys(dic).forEach(function (x) {
    var rendered = template(x, dic[x]);
    fs.writeFileSync('./output/' + x + ".html", rendered);
});
